
services:
  trainer:
    build: .
    command: ["python", "scripts/train.py"]
    volumes:
      - ./model:/app/model
    networks:
      - appnet

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model:ro
    depends_on:
      trainer:
        condition: service_completed_successfully
    networks:
      - appnet
    environment:
      - MODEL_WAIT_TIMEOUT=60

networks:
  appnet:
    driver: bridge
