version: "3.8"
services:
  trainer:
    build: .
    command: ["python","scripts/train.py"]
    volumes:
      - ./model:/app/model
    networks:
      - appnet

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    depends_on:
      - trainer
    networks:
      - appnet

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Copenhagen
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1234
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
